#!/usr/bin/env python3
"""
Checks that everything in assets/ and levels/ is what the tools produce.

Why not `git diff`: PNG files are compared by their pixels, not their bytes.
Two Pillow versions can encode the same image to different bytes, and a byte
comparison then fails on a machine whose Pillow differs from the one that
committed the file, which says nothing about whether the art is correct.

Run:  python3 tools/verify_generated.py
"""

import io
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOOLS = ["gen_art.py", "gen_levels.py", "gen_tileset.py"]


def committed(rel):
    """The file as HEAD has it, or None when HEAD does not have it."""
    r = subprocess.run(["git", "show", f"HEAD:{rel}"], cwd=ROOT,
                       capture_output=True)
    return r.stdout if r.returncode == 0 else None


def tracked(paths):
    r = subprocess.run(["git", "ls-files"] + paths, cwd=ROOT,
                       capture_output=True, text=True, check=True)
    return [line for line in r.stdout.splitlines() if line]


def same_image(a, b):
    from PIL import Image
    ia, ib = Image.open(io.BytesIO(a)), Image.open(io.BytesIO(b))
    if ia.size != ib.size:
        return False, f"{ib.size} -> {ia.size}"
    ia, ib = ia.convert("RGBA"), ib.convert("RGBA")
    if ia.tobytes() != ib.tobytes():
        differing = sum(1 for p, q in zip(ia.getdata(), ib.getdata()) if p != q)
        return False, f"{differing} pixels differ"
    return True, ""


def main():
    for tool in TOOLS:
        r = subprocess.run([sys.executable, os.path.join(ROOT, "tools", tool)],
                           cwd=ROOT, capture_output=True, text=True)
        if r.returncode != 0:
            print(f"tools/{tool} failed:\n{r.stdout}{r.stderr}")
            return 1

    problems = []
    for rel in tracked(["assets", "levels"]):
        if rel.endswith(".import"):
            continue  # Godot's own metadata, not generated by us
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            problems.append(f"{rel}: the tools no longer produce this file")
            continue
        now = open(path, "rb").read()
        was = committed(rel)
        if was is None:
            problems.append(f"{rel}: new, needs committing")
        elif rel.endswith(".png"):
            ok, detail = same_image(now, was)
            if not ok:
                problems.append(f"{rel}: {detail}")
        elif now != was:
            problems.append(f"{rel}: content differs")

    if problems:
        print("These do not match what the tools produce:")
        for p in problems:
            print(f"  {p}")
        print("\nRun the tools in tools/ and commit the result.")
        return 1

    print("assets/ and levels/ match the generators")
    return 0


if __name__ == "__main__":
    sys.exit(main())
